name: "Go Vulnerability Scanner"
description: "Scans Go dependencies for security vulnerabilities using govulncheck"
author: "Mahdi Mohammadi"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "shield"
  color: "red"
