name: Go Vulnerability Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-go-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
       
      - name: Run Go Vulnerability Scanner
        uses: ./